# Generated by Django 4.2 on 2023-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='owner',
        ),
    ]
